---
apiVersion: v1
kind: Namespace
metadata:
  name: policy-reporter
---
apiVersion: v1
kind: Secret
metadata:
  name: policy-reporter-config-email-reports
  namespace: policy-reporter
  labels:
    app.kubernetes.io/name: policy-reporter
type: Opaque
data:
  config.yaml: ZW1haWxSZXBvcnRzOgogIGNsdXN0ZXJOYW1lOgogIHNtdHA6CiAgICBob3N0OgogICAgcG9ydDoKICAgIHVzZXJuYW1lOgogICAgcGFzc3dvcmQ6CiAgICBmcm9tOgogICAgZW5jcnlwdGlvbjoKICBzdW1tYXJ5OgogICAgdG86IFtdCiAgICBmaWx0ZXI6CiAgICAgIG5hbWVzcGFjZXM6CiAgICAgICAgaW5jbHVkZTogW10KICAgICAgICBleGNsdWRlOiBbXQogICAgICBzb3VyY2VzOgogICAgICAgIGluY2x1ZGU6IFtdCiAgICAgICAgZXhjbHVkZTogW10KICB2aW9sYXRpb25zOgogICAgdG86IFtdCiAgICBmaWx0ZXI6CiAgICAgIG5hbWVzcGFjZXM6CiAgICAgICAgaW5jbHVkZTogW10KICAgICAgICBleGNsdWRlOiBbXQogICAgICBzb3VyY2VzOgogICAgICAgIGluY2x1ZGU6IFtdCiAgICAgICAgZXhjbHVkZTogW10=
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: policy-reporter
  namespace: policy-reporter
  labels:
    app.kubernetes.io/name: policy-reporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  name: policy-reporter
rules:
  - apiGroups:
      - '*'
    resources:
      - policyreports
      - policyreports/status
      - clusterpolicyreports
      - clusterpolicyreports/status
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: policy-reporter
roleRef:
  kind: ClusterRole
  name: policy-reporter
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: "ServiceAccount"
    name: policy-reporter
    namespace: policy-reporter
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: policy-reporter-summary-report
  namespace: policy-reporter
  labels:
    app.kubernetes.io/name: policy-reporter
    app.kubernetes.io/part-of: policy-reporter
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 300
      backoffLimit:  1
      ttlSecondsAfterFinished: 60
      template:
        metadata:
          labels:
            app.kubernetes.io/name: policy-reporter
            app.kubernetes.io/part-of: policy-reporter
        spec:
          serviceAccountName: policy-reporter
          automountServiceAccountToken: true
          securityContext:
            fsGroup: 1234
          restartPolicy: Never
          containers:
            - name: policy-reporter
              image: "ghcr.io/kyverno/policy-reporter:2.11.1"
              imagePullPolicy: IfNotPresent
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                privileged: false
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                runAsUser: 1234
                seccompProfile:
                  type: RuntimeDefault
              command:
                - /app/policyreporter
                - send
                - violations
              args:
                - --config=/app/config.yaml
                - --template-dir=/app/templates
              volumeMounts:
                - name: config-file
                  mountPath: /app/config.yaml
                  subPath: config.yaml
                  readOnly: true
          volumes:
            - name: config-file
              secret:
                secretName: policy-reporter-config-email-reports
                optional: true
